language: python
python:
    - "3.3"
    - "3.4"

install:
    - pip install coveralls

script:
    - python setup.py test
    - coverage run --source=skiplist setup.py test

after_success:
    coveralls
