language: python
python:
    - "3.4"
    - "2.7"
    - "3.3"

install:
    - pip install cpp-coveralls coveralls

script:
    - CFLAGS="-coverage" python setup.py build_ext --inplace
    - coverage run --source=skiplist setup.py test

after_success:
    - TRAVIS_JOB_ID=${TRAVIS_JOB_ID}C cpp-coveralls --build-root .
    - coveralls
